package io.github.kxng0109.aiprcopilot.api.dto;

import lombok.Builder;

import java.util.List;

/**
 * Represents the result of analyzing a code change diff.
 *
 * @param title            a brief summary of the analysis, must not be blank
 * @param summary          a concise description of the changes, must not be blank
 * @param details          detailed information about the changes, may be {@code null}
 * @param risks            potential risks or issues introduced by the changes, may be an empty list
 * @param suggestedTests   tests that should be added to verify the changes, may be an empty list
 * @param touchedFiles     files that were modified by the changes, must not be empty
 * @param analysisNotes    any additional notes or comments about the analysis, may be {@code null}
 * @param metadata         metadata about the response generated by an AI model, never {@code null}
 * @param requestId        a unique identifier for the request, may be {@code null}
 * @param rawModelOutput   the raw output from the AI model, may be {@code null}
 */
@Builder
public record AnalyzeDiffResponse(
        String title,
        String summary,
        String details,
        List<String> risks,
        List<String> suggestedTests,
        List<String> touchedFiles,
        String analysisNotes,
        AiCallMetadata metadata,
        String requestId,
        String rawModelOutput
) {
}
