package io.github.kxng0109.aiprcopilot.config.api.dto;

import lombok.Builder;

/**
 * Represents metadata about the response generated by an AI model.
 *
 * @param modelName the name of the AI model used to generate the response, must not be blank
 * @param modelLatencyMs the latency in milliseconds it took for the model to generate the response, must be non-negative
 * @param tokensUsed the number of tokens consumed by the model to generate the response, may be {@code null} if not applicable
 */
@Builder
public record AiCallMetadata(
        String modelName,
        long modelLatencyMs,
        Integer tokensUsed
) {
}
